export const actionTypes = {
    GET_POSTS_INIT: 'GET_POSTS_INIT',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
    GET_CURRENT_POST_INIT: 'GET_CURRENT_POST_INIT',
    GET_CURRENT_POST_SUCCESS: 'GET_CURRENT_POST_SUCCESS',
    GET_CURRENT_POST_FAILURE: 'GET_CURRENT_POST_FAILURE',
    CREATE_POST_INIT: 'CREATE_POST_INIT',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',
    SET_FIELD_VALUE: 'SET_FIELD_VALUE',
    CLEAR_STORE: 'CLEAR_STORE',
};
